name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: appleboy/ssh-action@v2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rsync -av --exclude='.git*' --exclude='node_modules' ./ user@your-server:/var/www/html/wordpress

  notify:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Notify on Deployment
        uses: rtCamp/action-slack-notify@v2
        with:
          status: ${{ job.status }}
          text: "Deployment to production is complete!"
