name: Build and Deploy Locally

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build-and-deploy-locally:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache npm dependencies
        id: npm-cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.16.0"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer:v2

      - name: Install npm and Composer dependencies
        run: |
          npm ci
          composer install

      - name: Build Theme
        run: npm run prod
        working-directory: themes/twentytwentyone

      - name: Deploy Locally
        run: |
          npm install
          npm run build

      - name: Set Permissions Locally
        run: |
          # Add your permission-setting steps here, for example:
          echo "Set permissions steps go here"
          chown -R www-data:www-data /var/www/html/wordpress/wp-content/themes
