name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: var/www/html/wordpress  # Assuming your WordPress files are in the root directory of your repository

  notify:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Notify on Deployment
        uses: rtCamp/action-slack-notify@v2
        with:
          status: ${{ job.status }}
          text: "Deployment to production is complete!"
